### ISSUE TITLE
StatusCodeError: 403 

### ISSUE THREAD

**Issue by Exzender** [go-faast/blockbook-client#9]
Requests now return with error.

`StatusCodeError: 403 - "error code: 1020"`

Possibly because of Cloudflare protection.

Adding of User-Agent in **jsonRequest** solves an issue
`        const fullOptions = {
            method,
            body,
            json: true,
            ...options,
            headers: {"User-Agent": 'Any'}
        };`

**Comment by dylanseago** [comment]
Fixed in v0.4.0
